CSCfi/oiva-frontend

src/index.js, src/modules/elements.js, src/modules/styles.js, src/routes/Home/components/Home.js, src/routes/Jarjestajat/Jarjestaja/components/Jarjestaja.js, src/routes/Jarjestajat/Jarjestaja/components/Jarjestamislupa.js, src/routes/Jarjestajat/Jarjestaja/components/JulkisetTiedot.js, src/routes/Jarjestajat/Jarjestaja/components/Koulutusala.js, src/routes/Jarjestajat/Jarjestaja/components/OmatTiedot.js, src/routes/Jarjestajat/Jarjestaja/components/ProfileMenu.js, src/routes/Jarjestajat/Jarjestaja/components/Section.js, src/routes/Jarjestajat/Jarjestaja/components/Tutkinto.js, src/routes/Jarjestajat/Jarjestaja/containers/JarjestamislupaContainer.js, src/routes/Jarjestajat/Jarjestaja/modules/lupa.js, src/routes/Jarjestajat/components/Jarjestajat.js, src/routes/Jarjestajat/modules/luvat.js, src/static/images/koulutusala-arrow.svg
=> CSCOIVA-367

src/routes/Jarjestajat/Jarjestaja/components/LupaHistoryItem.js, src/routes/Jarjestajat/Jarjestaja/modules/history.js
=> Lisätty luvan voimassaolon käsittely

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/KoulutusList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPerustelut.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardTutkinnot.js
=> Kohteen 1 ulkoasun ja toiminnallisuuden muutokset

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/KieliSelect.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardComponents.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardTutkintokielet.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/TutkintoKieliList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js
- Tutkintokielet ovat puumallina (listattu vain luvassa olevat tutkinnot)
- Valittujen tutkintokielten arvo säilyy vaiheiden yli
Issue: CSCOIVA-449
=> Kohteen 2 uudistukset

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/constants.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/kieliUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/oppilaitoksenopetuskielet.js
- Poistettu turhat sanat teksteistä
- Opetuskielen järjestys on nyt: Suomi, Ruotsi, Saame
Issue: CSCOIVA-450
=> Kohteen 2 pienet viilaukset

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardComponents.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuutokset.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPerustelut.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js
- Peruuta-napit poistettu
- edellinen-nappi vasemmassa laidassa ja seuraava-nappi oikeassa laidassa
Issue: CSCOIVA-458
=> Muutospyynnön ulkoasun muokkauksia

package-lock.json, package.json, src/modules/styles.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/ModalComponents.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardComponents.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuutokset.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPaatoskierros.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPerustelut.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/muutosperusteluUtil.js
- uusi rakenne hallintapainikkeille
- tyylit hallintapainikkeille
- dialogikomponentti: otettu käyttöön react-modal
- muutoshakemuksen peruutukselle dialogi
Issues: CSCOIVA-458, CSCOIVA-463
=> Muutosperustelun hallintapainekkeet ja dialogi-komponentti

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js
=> Hakemuksen lähetykseen lisätty dialogi

package-lock.json, package.json, src/modules/DatePicker.js, src/modules/styles.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/KoulutusList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutosList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutosYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardComponents.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPerustelut.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/OrganisaationTiedot.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluSimple.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/kieliUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/muutosperusteluUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/uusiHakemusFormConstants.js
- toteutettu oma komponentti muutoksien listaukselle yhteenvedossa
- organisaation tiedot (opintopolusta) yhteenvedossa
- hakijan yhteyshenkilön tiedot yhteenveto-sivulla
- DatePicker-komponentti toteutettu
- datepickerillä valitaan muutosten haluttu alkupvm
Issues: CSCOIVA-457, CSCOIVA-464
=> Yhteenvedon toteutus

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Muutos.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoEditWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/muutospyyntoUtil.js, src/routes/Jarjestajat/Jarjestaja/components/LupaSection.js
- järjestämisluvan virhe korjattu
- hakijan tiedot ladataan kannasta/statesta
Issue: CSCOIVA-491
=> KJ:n puolen parannuksia ja korjauksia

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/TutkintoKieliList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/TutkintoList.js
Järjestä tutkintolistat muutospyynnön kohdissa 1. ja 2. tutkinnon koodin perusteella.
Molemmat tiketit samassa commitissa, koska muutokset olivat lähes identtiset.
=> CSCOIVA-504, CSCOIVA-505 Järjestä listoja

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardToimialue.js
Muutettu kaksi väliotsikkoa ja valtakunnallinen-valintaruutuun liittyvä teksti.
=> Tekstimuutoksia muutospyynnön toiminta-alueeseen

src/routes/Home/components/Home.js, src/routes/Tilastot/components/Tilastot.js
Etusivun palautelinkki ja tilastosivun linkit avataan uusiin välilehtiin.
=> CSCOIVA-602, CSCOIVA-603 Avaa linkkejä uusiin tabeihin

src/routes/Jarjestajat/Jarjestaja/components/Jarjestaja.js, src/routes/Jarjestajat/Jarjestaja/components/JarjestajaBasicInfo.js
Poistettu osoitetiedot Koulutuksen järjestetän tiedot -sivulta. 
Korjattu murupolkuun Ammatillinen koulutus.
=>  CSCOIVA-628: Poistettu osoitetiedot ja korjattu murupolun teksti

src/routes/Jarjestajat/Jarjestaja/components/Jarjestaja.js, src/routes/Jarjestajat/Jarjestaja/components/Jarjestamislupa.js, src/routes/Jarjestajat/Jarjestaja/components/LupaSection.js, src/routes/Jarjestajat/Jarjestaja/components/MuuMaarays.js
Tabien teksti muutettu. Lisätty pvm otsikkoon. Poistettu tietoja. Parannettu layouttia: tasaukset ja marginaalit kuntoon.
=> Cscoiva 629: Järjestämisluvan sisältö

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/TutkintoList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js
Korjauksia muutospyynnön tutkintojen lisäys/poistovalintoihin, joita meni rikki väliotsikkouudistuksessa ja JSON-refaktoroinnissa.
=> CSCOIVA-643: Muutospyynnön bugikorjauksia

package-lock.json, package.json, src/modules/Table.js, src/routes/Jarjestajat/Jarjestaja/components/Jarjestaja.js, src/routes/Jarjestajat/Jarjestaja/components/Jarjestamislupa-asiat.js, src/routes/Jarjestajat/Jarjestaja/components/Jarjestamislupa.js, src/routes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiakirjat.js, src/routes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiakirjatItem.js, src/routes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiatList.js, src/routes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiatListItem.js, src/routes/Jarjestajat/Jarjestaja/components/JulkisetTiedot.js, src/routes/Jarjestajat/Jarjestaja/components/LupaHistory.js, src/routes/Jarjestajat/Jarjestaja/components/LupaSection.js, src/routes/Jarjestajat/Jarjestaja/components/ProfileMenu.js, src/routes/Jarjestajat/Jarjestaja/containers/JarjestamislupaAsiatContainer.js, src/routes/Jarjestajat/Jarjestaja/modules/constants.js
UI pohja taulukoille.
Näkyy kirjautumisen jälkeen.
=> Cscoiva 632: Järjestämislupa-asiat

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardComponents.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuut.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelu.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/constants.js
CSCOIVA-676
CSCOIVA-668
CSCOIVA-669
CSCOIVA-670
=> Cscoiva 676: Lomakkeen 5-kohdan muutoksia

src/modules/elements.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/KoulutusList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoEditWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuut.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelu.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/uusiHakemusFormConstants.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/components/HakemuksetJaPaatokset.js
WIP: Refactoroida koulutusUtil.js:n ehdot uusiksi.
=> Cscoiva 671: Ehdot kuntoon lomakkeen 5-kohdan perusteluille

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/muutospyynto.js
Uudelleen latauksessa puuttuu tietoa: selvitettävä.
=> Cscoiva 691: Hakemuksen tallennus korjattu

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardComponents.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Taloudelliset.js
Lisää muutospyynnön yhteenvetonäkymään saate-kentän.
=> CSCOIVA-672 Muutospyynnön saate

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Muutos.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutosListTutkinnot.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelu.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluKuljettajaJatko.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluKuljettajaPerus.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js
Perusteluissa ei näytetä kuljettajakoulutuksen perustelulomaketta koodiarvon vaan merkityksen mukaan.
=> CSCOIVA-684: Valitse kuljettajakoulutuksen perustelulomake merkityksen mukaan

src/routes/Asiat/Valmistelu/components/Muutos.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Liite.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Muutos.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelu.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/muutospyynto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/muutospyyntoUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/modules/muutokset.js
=> Cscoiva 691: Liitteen tallennus 

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js
Muutospyynnön yhteenvedossa näytetään kentät "nimike" ja "hyväksyjän/allekirjoittajan nimike".
=> CSCOIVA-689 Lisää muutospyyntöön henkilöiden nimikkeet

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/MuutospyyntoEditWizardContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/MuutospyyntoWizardContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/muutospyynto.js, src/routes/Login/containers/CasAuthenticated.js
Muutospyynnön lähettäminen korjattu.
=> Cscoiva 724

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Liitteet.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPerustelut.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/uusiHakemusFormConstants.js
forceUnregisterOnUnmount: true
=> Tuhotaan formin sisältö kun komponentti suljetaan ja liitteen korjaukset

src/modules/Header/components/Header.js, src/modules/constants.js, src/routes/Login/modules/user.js
- Logout suoritetaan ensiksi backendille, joka käskee selaimen kirjautumaan ulos
opintopolusta.
=> CSCOIVA-728 Korjaus käyttäjä kirjautumiseen ja roolitukseen.

package-lock.json, package.json, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Muutos.js
Plus muutoksen ehtolauseke korjattu.
=> Node-sass tuki+ tailwindcss

src/scenes/Jarjestajat/Jarjestaja/components/Jarjestaja.js, src/scenes/Jarjestajat/Jarjestaja/components/Jarjestamislupa.js, src/scenes/Jarjestajat/Jarjestaja/components/JulkisetTiedot.js, src/scenes/Jarjestajat/Jarjestaja/components/LupaSection.js, src/scenes/Jarjestajat/Jarjestaja/components/ProfileMenu.js, src/scenes/Jarjestajat/Jarjestajat.js, src/scenes/Jarjestajat/components/LuvatList.js
First "tailwinded" version of the Jarjestajat section. Changes are mostly related to the common layout. Menu is improved for smaller screen too.
=> Layout of the Jarjestajat section updated.

src/modules/styles.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Liite.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Liitteet.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardComponents.js, src/routes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiakirjatItem.js, src/routes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiatList.js, src/routes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiatListItem.js
Tyylit korjattu Tailwindin css:n asennyksen jäljiltä
=> CSCOVA 781: QA:n korjaukset

src/css/tailwind.css, src/css/tailwind.src.pcss
Lisätty tarvittavat tyylit headereille.
=> h1, h2, h3, h4 tyylit korjattu

src/components/01-molecules/CheckboxWithLabel/checkboxWithLabel.stories.js, src/components/01-molecules/CheckboxWithLabel/index.js, src/css/label.js
=> More reusable checkbox with a label.

src/components/02-organisms/ExpandableRowRoot/index.js, src/i18n/definitions/common.js, src/i18n/locales/fi.json, src/i18n/locales/sv.json, src/i18n/messages/messages.json, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuut.js
Lomakkeen 5-kohtaan petuutus toimimaan.
Peruutuksen napin ikoni muutettu ja tooltip lisätty.
Napin painaminen ei sulje kyseistä osioita.
=> Csckuja 80: Muutosten peruuttaminen

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardToimintaalue.js, src/services/muutoshakemus/utils/toiminta-alue.js
Lisätty myös puuttuneet dependencyt.
=> Kuntien ja maakuntien lisääminen korjattu (Osio 3).

src/services/muutoshakemus/utils/opetus-ja-tutkintokieli.js
Real "maaraystyyppi" value used.
=> CSCOIVA-734: Added real "maaraystyyppi" value into use

src/context/muutoshakemusContext.js, src/context/muutospyynnotContext.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuutokset.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardToimintaalue.js
Muutokset on mahdollista välittää lomakkeen ensimmäisen sivun osioille.
=> Tallennetun luonnoksen muutokset voidaan välitetään eteenpäin.

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Kielet/Opetuskielet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Kielet/Tutkintokielet.js, src/services/muutoshakemus/utils/opetus-ja-tutkintokieli.js, src/services/muutoshakemus/utils/saving.js
+ Drafts for tutkintokielet data handling
=> Cscoiva 734: null checks

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Kielet/Tutkintokielet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardKielet.js, src/services/muutoshakemus/utils/opetus-ja-tutkintokieli.js
=> Cscoiva 734: Tutkintokielet saving (without meta)

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardToimintaalue.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Valtakunnallinen/index.js, src/services/muutoshakemus/utils/saving.js, src/services/muutoshakemus/utils/toiminta-alue.js
UI handling and saving (addition). WIP for removing and loading state back.
=> Cscoiva 895: Valtakunnallinen

package-lock.json
Fixed eslint-utils package vulnerability.
=> Cscoiva 921: Package update

src/components/01-molecules/RadioButtonWithLabel/radioButtonWithLabel.stories.js
Tosiaan tässäpä nämä stoorit. Toimivat ainakin minulla.
=> Created stories for radio button

src/components/02-organisms/CategorizedListRoot/CategorizedList/index.js
Fixed margins and added resposive layout for autocomplete and textbox in CategorizedList.
=> Fixed margins and added resposive layout for autocomplete and textbox.

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Kielet/Tutkintokielet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardKielet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuutokset.js
Anchor-toteutuksen päivitys aiheutti tarpeen näille koodimuutoksille.
=> 1. ja 3. osioiden välinen kommunikaatio päivitetty.

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Kielet/Tutkintokielet.js
=> Tutkintokielet-aliosion kohtia ei näytetä boldattuna.

src/components/02-organisms/CategorizedListRoot/index.js, src/components/02-organisms/CategorizedListRoot/storydata/simpleStory.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuut.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuutokset.js
=> Näytetään vain lupaan kuuluvien koodiarvojen mukaiset kohdat osiossa 5.

src/components/02-organisms/ExpandableRowRoot/index.js, src/css/tailwind.src.pcss, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Kielet/TutkintokieliList.js
Font family to support better semibold.
Using header levels in lists.
Margin fixes to category list.
=> Font and margin tweakings

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Valtakunnallinen/index.js
=> Added added, removed and in lupa styles for Valtakunnallinen

src/components/00-atoms/Input/index.js, src/components/00-atoms/Input/input.stories.js, src/components/02-organisms/Attachment/index.js, src/components/02-organisms/CategorizedListRoot/CategorizedList/index.js, src/components/04-forms/koulutukset/Kuljettajakoulutukset/Peruskoulutuslomake/index.js, src/components/04-forms/muut/VankilaopetusPerustelulomake/index.js, src/components/04-forms/muut/VankilaopetusPerustelulomake/vankilaopetusPerustelulomake.stories.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/ModalComponents.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelut/PerustelutKuljettajakoulutukset.js, src/services/lomakkeet/perustelut/muut.js
WIP: Need to change opiskelijavuodet into a component
=> Cscoiva 937: Perustelut, vankilaopetus

src/components/00-atoms/Input/index.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Hakemus/hakemusContainer.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Taloudelliset/TaloudellisetInvestoinnit.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Taloudelliset/TaloudellisetTilinpaatostiedot.js, src/services/muutoshakemus/utils/saving.js
Liitteiden käsittely eri issuella.
=> Saving / loading data works except for attachments handling.

src/scenes/Jarjestajat/Jarjestaja/components/Jarjestaja.js, src/scenes/Jarjestajat/Jarjestaja/components/Jarjestamislupa-asiat.js, src/scenes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiatList.js
Removed the unwanted "Järjestämisluvan peruutus" button
Moved the "Uusi hakemus" button NavLink functionality down the hierarchy
Removed the NavLink from tab nav.
=> Csckuja 174

src/components/02-organisms/Attachments/index.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Hakemus/hakemusContainer.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/WizardPage.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Yhteenveto/YhteenvetoLiitteet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Yhteenveto/YhteenvetoYleisetTiedot.js, src/services/muutoshakemus/actions.js, src/services/muutospyynnot/muutospyyntoUtil.js
uuid handling for attachments:
loading
saving
=> Cscoiva 959: UUIDs

package-lock.json, package.json, src/components/02-organisms/Autocomplete/index.js, src/scenes/Asiat/Valmistelu/components/Paatos.js, src/scenes/Asiat/Valmistelu/components/ValmisteluTutkinnot.js, src/scenes/Asiat/Valmistelu/components/ValmisteluWizard.js, src/scenes/Asiat/components/AvoimetAsiat.js, src/scenes/Asiat/components/PaatetytAsiat.js, src/scenes/Asiat/components/ValmistelussaAsiat.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Hakemus/hakemusContainer.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Hakemus/index.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Muutospyynto.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoEditWizard.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardOpiskelijavuodet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPerustelut.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardTutkintokielet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelu.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluSimple.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluTyovoimaYhteenveto.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVankilaYhteenveto.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelut/PerustelutMuut.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelut/PerustelutToimintaalue.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Yhteenveto/YhteenvetoTaloudelliset.js, src/scenes/Jarjestajat/Jarjestaja/components/Jarjestaja-old.js, src/scenes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiakirjat.js, src/services/lomakkeet/perustelut/muut.js
Package updates, UNSAFE prefix in use, prisons are listed on Perustelut page, z-index fix for react-select, got rid of some warnings.
=> Cscoiva 910 5

src/components/02-organisms/Difference/difference.stories.js, src/components/02-organisms/Difference/index.js, src/components/04-forms/muut/OpiskelijavuodetLomake/SisamuotoinenOpetus/index.js, src/components/04-forms/muut/OpiskelijavuodetLomake/VaativaKoulutus/index.js, src/components/04-forms/muut/OpiskelijavuodetLomake/Vahimmaisopiskelijavuosimaara/index.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelut/PerustelutOpiskelijavuodet.js, src/services/lomakkeet/perustelut/common.js, src/services/lomakkeet/perustelut/muut.js
Fixed PerustelutOpiskelijavuodet to determine the existence of changes from opiskelijavuodet instead of perustelut.
Made Difference have a read-only mode and expanded its stories.
Now using the read-only Difference as part of PerustelutOpiskelijavuodet (in Perustelut and Yhteenveto) view to show the applied differences in amounts.
=> Cscoiva 976

src/components/01-molecules/CheckboxWithLabel/index.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Hakemus/hakemusContainer.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelut/PerustelutLiitteet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Taloudelliset/TaloudellisetLiitteet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Taloudelliset/TaloudellisetYleisettiedot.js, src/services/muutoshakemus/actions.js, src/services/muutospyynnot/muutospyyntoUtil.js
=> CSCOIVA-1010: Fixed setAttachmentUuids preventing Taloudelliset working

src/components/02-organisms/Attachments/FileDownloader.js, src/components/02-organisms/Attachments/index.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/HakemusContainer.js
=> Cscoiva 787: Fixing loading of form after refactoring.

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/WizardActions.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/WizardPage.js, src/services/muutoshakemus/actions.js, src/services/muutoshakemus/reducer.js
Make "preview" button save the application and trigger downloading its preview pdf.
=> Cscoiva 1024

src/App.js, src/AppWrapper.js
=> More code comments.

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/services/muutoshakemus/actions.js
Now properly allowing submit failure situation to show in ui toast
=> slight refactor to clarify intent and fix wrong actions in submit

src/components/02-organisms/CategorizedListRoot/Stage/index.js, src/components/02-organisms/CategorizedListRoot/utils.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuutokset.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPerustelut.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardToimintaalue.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelut/PerustelutToimintaalue.js, src/scenes/Jarjestajat/Jarjestaja/components/Jarjestaja.js, src/services/muutoshakemus/utils/changes-to-save.js
The changes are mostly made by the formatter (Prettier). The actual relevant change is in changes-to-save.js lines 307 - 326.
=> Bug fix. Maakuntien poistaminen korjattu.

src/components/02-organisms/SimpleMenu/index.js, src/components/02-organisms/Table/TableCell/index.js, src/components/02-organisms/Table/index.js, src/scenes/Jarjestajat/Jarjestaja/components/Jarjestaja.js, src/scenes/Jarjestajat/Jarjestaja/components/Jarjestamislupa-asiat.js, src/scenes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiatList.js, src/scenes/Jarjestajat/Jarjestaja/components/JulkisetTiedot.js, src/scenes/Jarjestajat/Jarjestaja/components/LupaHistory.js, src/utils/common.js
CSCKUJA-60-kayttoonotto was a temporary name for this branch.  The code is for CSCOIVA-1047.
=> CSCOIVA-1047

src/i18n/definitions/common.js, src/i18n/locales/fi.json, src/i18n/locales/sv.json, src/i18n/messages/messages.json, src/scenes/EsiJaPerusopetus/components/EsiJaPerusopetus.js, src/scenes/Lukiokoulutus/components/Lukiokoulutus.js, src/scenes/VapaaSivistystyo/components/VapaaSivistystyo.js, tests/e2e/specs/esi-ja-perusopetus.spec, tests/e2e/specs/lukiokoulutus.spec, tests/e2e/specs/vapaa-sivistystyo.spec, tests/e2e/tests/step_implementation.js
* New translation added
* E2E tests done
=> Csckuja 213

src/scenes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiakirjat.js, src/scenes/Jarjestajat/Jarjestaja/components/JarjestamislupaAsiatList.js, src/scenes/Jarjestajat/Jarjestaja/modules/constants.js, src/scenes/Tilastot/components/Tilastot.js
Esittelijä part will need own ticket.
=> csckuja-221: State text changes and logic (KJ part)

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelut/PerustelutKuljettajakoulutukset.js
Added more codes values (koodiarvot) to form selection for Kuljettajakoulutus.
This was because of code value changes.
=> CSCOIVA-1036: FIx for kuljettajakoulutus forms

src/services/muutoshakemus/utils/saving.js
Taloudelliset edellytykset part only.
Continuing to yhteenveto + perustelut.
=> Cscoiva 1069: Fixed tuloudelliset saving.

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Yhteenveto/YhteenvetoYleisetTiedot.js, src/services/muutoshakemus/utils/saving.js
Yhteenveto values to backend save.
Voimassaalkupvm from correct value.
=> Cscoiva 1069

src/components/00-atoms/Input/index.js, src/components/00-atoms/Input/input.pcss, src/components/00-atoms/TextBox/index.js, src/components/00-atoms/TextBox/textbox.pcss, src/components/02-organisms/CategorizedListRoot/CategorizedList/components/CategorizedListTextBox.js, src/components/02-organisms/CategorizedListRoot/CategorizedList/index.js, src/components/02-organisms/Tooltip/index.js, src/i18n/definitions/wizard.js, src/i18n/locales/fi.json, src/i18n/locales/sv.json, src/i18n/messages/messages.json, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Taloudelliset/TaloudellisetInvestoinnit.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Taloudelliset/TaloudellisetYleisettiedot.js
Run `npm run build:component-css` to build new .pcss files.
=> Question mark icons and tooltips with i18n localized texts added.

src/scenes/Asiat/Valmistelu/modules/valmisteluUtils.js, src/services/lomakkeet/perustelut/common.js, src/services/lomakkeet/perustelut/koulutukset.js, src/services/lomakkeet/perustelut/lomakeosiot/kuljettajakoulutukset.js, src/services/muutoshakemus/utils/changes-to-save.js, src/services/muutoshakemus/utils/koulutusperustelut.js, src/utils/lupaParser.js
=> Cscoiva 1069: Perustelut saving

src/services/lomakkeet/backendMappings/all-mappings.js, src/services/lomakkeet/backendMappings/calculate.js, src/services/lomakkeet/backendMappings/index.js, src/services/lomakkeet/backendMappings/mappings/opiskeluvuodet.js, src/services/lomakkeet/backendMappings/mappings/tutkinnot.js, src/services/lomakkeet/backendMappings/mappings/vaativaerityinentuki.js, src/services/muutoshakemus/utils/changes-to-save.js
+ fixes for perustelut inc. vaativaerityinentuki.
=> Cscoiva 1093: Common mapping for koulutukset etc.

src/services/lomakkeet/muut/index.js, src/services/lomakkeet/perustelut/muutMuutokset/index.js, src/services/lomakkeet/utils.js
* "Huomioitava koodi" is not part of an article (määräys) so it can't be used for arranging the list items. This might be a problem.
=> Order of list items fixed but this might not be enough.

src/routes/Asiat/Valmistelu/components/ValmisteluWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Muutospyynto.js, src/routes/Jarjestajat/Jarjestaja/components/CurrentLupa.js, src/routes/Jarjestajat/Jarjestaja/components/JulkisetTiedot.js, src/routes/Jarjestajat/Jarjestaja/components/LupaHistoryItem.js
Can be tested using CSCOIVA-1132 backend branch ( from 1.9.8_hotfix) only
=> Replace pdf endpoints with diaarinumero by uuid

package-lock.json, package.json
Paketin päivitys. Lisää koodia myöhemmin.
=> okm-frontend-components upgraded to version 0.3.3

src/i18n/locales/sv.json, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/uusiHakemusFormConstants.js, src/services/lomakkeet/perustelut/common.js, src/services/lomakkeet/perustelut/koulutukset/atv-koulutukset/index.js, src/services/lomakkeet/perustelut/koulutukset/kuljettajakoulutukset/peruskoulutus/index.js, src/services/lomakkeet/perustelut/koulutukset/valmentavatKoulutukset/index.js, src/services/lomakkeet/perustelut/tutkinnot/index.js
And added some required messages for testing.
=> Removed placeholders

src/routes/Jarjestajat/Jarjestaja/components/LupaHistoryItem.js
Simplified and separated api call for lupahistoria pdf files
Backend implementation: https://github.com/CSCfi/oiva-backend/pull/214
=> CSCOIVA-1182

package-lock.json, package.json, src/components/02-organisms/procedureHandler/procedures/muutospyynto/muutokset/poista.js, src/components/03-templates/FormSection/index.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuut.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuutokset.js, src/services/lomakkeet/locales/fi.json, src/services/lomakkeet/locales/sv.json, src/services/lomakkeet/muut/index.js, src/services/lomakkeet/muut/utils.js, src/services/lomakkeet/perustelut/muutMuutokset/index.js, src/services/lomakkeet/tutkinnot/index.js
* Wizard dialog will be smoothly scrollable.
* Alert dialogs on section 5 depending on the value of koodiArvo. Alert won't be shown for all code values, only for radio buttons of Vaativa tuki and for Sisäoppilaitos.
* Scrolling to Opiskelijavuodet section when the link of an Alert has been clicked.
=> CSCOIVA-1166

src/i18n/definitions/common.js, src/i18n/locales/fi.json, src/i18n/locales/sv.json, src/i18n/messages/messages.json, src/scenes/Esittelijat/Esittelijat.js
=> Button for creating a new thing added.

src/scenes/Esittelijat/components/AvoimetAsiat.js, src/scenes/Esittelijat/components/PaatetytAsiat.js, src/scenes/Esittelijat/modules/asiatUtils.js, src/stores/muutospyynnotEsittelijaValmistelussa.js
State setting to Valmistelussa = Esittelyssä.
Getting Valmistelussa stated data separately as backend does not support getting all states at once. Removed unnecessary filtering, concat instead.
=> CSCOIVA-1203

src/scenes/Home/index.js
Text change from production to OIVA.
=> CSCKUJA-366: Text change

package.json, src/App.js, src/scenes/Esittelijat/Esittelijat.js, src/scenes/Esittelijat/modules/asiatUtils.js, tailwind.js
Updated OKM library and tailwind settings. Fixed Asiat view to use it better.
=> CSCOIVA-1196: Theme update for Oiva

src/AppWrapper.js, src/stores/localizations.js, src/stores/utils/backendRoutes.js
Create file .env.development.local and add the following line on it: REACT_APP_FETCH_LOCALICATIONS_FROM_BACKEND=true
=> Implementation for fetching the localizations from the backend.

src/components/02-organisms/procedureHandler/procedures.js, src/components/02-organisms/procedureHandler/procedures/muutospyynto/tallennus/tallennaEsittelijanToimesta.js, src/scenes/Esittelijat/Esittelijat.js, src/scenes/Esittelijat/EsittelijatMuutospyynto.js, src/scenes/Esittelijat/EsittelijatWizardActions.js, src/scenes/Esittelijat/UusiAsiaDialog.js, src/scenes/Esittelijat/UusiAsiaDialogContainer.js, src/scenes/Esittelijat/components/Asiakirjat.js, src/scenes/Esittelijat/components/Asiat.js, src/scenes/Esittelijat/components/AvoimetAsiat.js, src/scenes/Esittelijat/components/PaatetytAsiat.js, src/services/lomakkeet/esittelija/index.js, src/services/muutoshakemus/utils/saving.js, src/stores/utils/backendRoutes.js
Key features of the PR related to the issue CSCOIVA-1205:
* Luo uusi asia button and its event handler
* Small dialog that opens on a click of the Luo uusi asia button
* Opening of a muutospyyntö form for esittelijä role
* Top three fields of the form (asianumero, päätöspäivä, voimaantulopäivä)
* Rest of the form
* Form actions (close, save, preview)
* Layout of the form (needs finalizing on a later issue)
* Unsaved document (the form) can be acccessed via url (uusi)
* Redirection to freshly saved muutospyyntö document
* Saved document can be accessed via url (uuid)
* Navigation and structure of Esittelijät pages slighly refactored (e.g. reduced amount of component parameters, useHistory and some other React hooks in use now)
=> Includes code of multiple Jira issues

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Koulutukset/Kuljettajakoulutukset.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Koulutukset/Tyovoimakoulutukset.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Koulutukset/ValmentavatKoulutukset.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardKoulutukset.js, src/utils/koulutusUtil.js
- Now VALMA / TELMA is checked if found from lupa.
=> CSCOIVA-1299 Fixed VALMA/TELMA form.

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Koulutukset/ATVKoulutukset.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardKoulutukset.js
- Now all ATVkoulutukset should be checked if found from lupa.
=> CSCOIVA-1281 Fixed ATVKoulutukset.

package-lock.json, package.json, src/scenes/Esittelijat/components/AvoimetAsiat.js
Confirm modal in AsiatList now using ConfirmDialog spinner / disable feature during backend call
=> Cscoiva 1268

src/css/tailwind.src.pcss
=> CSCOIVA-1404: Murupolun linkkien väri ei ole saavutettava

src/components/03-templates/Section/index.js
chore: combining of h2 elements to make voiceover experience better
=> CSCOIVA-1363: Lupanäkymän duplikaatit H2 elementit

src/scenes/Jarjestajat/Jarjestaja/components/ProfileMenu.js
chore: nav tag added for better VoiceOver experience.
=> CSCOIVA-1356: Navigaatioiden ja aktiivisen kohteen aria attribuutit

src/scenes/Footer/Footer.js
Underlining added as a minor improvement
=> fix: link paths

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/components/MuutospyyntoList.js, src/scenes/Jarjestajat/Jarjestaja/components/JulkisetTiedot.js, src/scenes/Jarjestajat/Jarjestaja/components/Lupapaatokset.js, src/scenes/Jarjestajat/Jarjestaja/components/LupapaatoksetTable/index.js
* nykyinen lupa lisätty aiempiakin lupia näyttävään taulukkoon.
=> CSCOIVA-1465: Nykyinen lupa täytyy näyttää samassa taulukossa aiempien lupapäätösten kanssa

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuut.js
* Avautuvien alueiden otsikot tulevat tämän PR:n myötä koodistosta
* Järjestys asetettu tiketin [CSCOIVA-1467](https://jira.eduuni.fi/browse/CSCOIVA-1467) mukaiseksi
=> CSCOIVA-1467: Järjestys kohdassa 5 Muut oikeudet, velvollisuudet, ehdot ja tehtävät

src/scenes/Esittelijat/UusiAsiaDialog.js
Backend-toteutuksesta oma issue.
=> CSCOIVA-1471: Tallentamisen tulee olla mahdollista virheistä huolimatta.

src/scenes/Jarjestajat/components/Jarjestajaluettelo.js
=> CSCOIVA-1491: Linkit koulutuksenjärjestäjien taulukossa tulisi viedä järjestämislupaan

src/AppWrapper.js, src/i18n/definitions/common.js, src/i18n/locales/fi.json, src/i18n/locales/sv.json, src/i18n/messages/messages.json, src/scenes/BaseData/index.js, src/scenes/Esittelijat/EsittelijatMuutospyynto.js, src/scenes/Esittelijat/UusiAsiaDialog.js, src/scenes/Esittelijat/UusiAsiaDialogContainer.js, src/scenes/Esittelijat/UusiAsiaEsidialog.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Kielet/Tutkintokielet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardKielet.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardToimintaalue.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Tutkinnot/index.js, src/services/muutoshakemus/utils/saving.js, src/stores/utils/backendRoutes.js, src/utils/lupaParser.js
Uutta lupaa haettaessa ei voida käyttää olemassa olevaa lupaa hyväksi, koska sellaista ei ole. Toteutuksessa on käyty läpi kohdat, joissa on oletettu luvan olevan olemassa ja varmistettu, etteivät tällaiset kohdat aiheuta virhetilanteita.
=> CSCOIVA-1492: Kokonaan uuden ammatillisen koulutuksen-luvan syöttäminen - syöttölomake

src/scenes/BaseData/index.js, src/scenes/Esittelijat/UusiAsiaDialog.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuut.js, src/services/lomakkeet/muut/index.js, src/stores/utils/backendRoutes.js
Yhteistyösopimuskohta lisätty osioon 5.
=> CSCOIVA-1322: Luvassa olevat yhteistyösopimukset eivät näy kohteessa 5 muokkausnäkymässä (Kohta 5. Muut)

src/AppWrapper.js, src/scenes/Esittelijat/UusiAsiaDialog.js, src/scenes/Jarjestajat/Jarjestaja/components/Jarjestamislupa.js, src/scenes/Jarjestajat/Jarjestajat.js, src/scenes/Login/Login.js
H1-tason otsikko muutettu H2-tasoiseksi.
=> CSCOIVA-1461: Koulutuksenjärjestäjä-näkymissä on kaksi 1. tason otsikkoa

src/scenes/Home/index.js, src/scenes/Jarjestajat/Jarjestaja/components/Jarjestaja.js, src/scenes/Jarjestajat/Jarjestajat.js, src/scenes/Tilastot/components/Tilastot.js
* Title-attribuutit päivitetty tehtävänannon mukaisesti.
=> CSCOIVA-1499: Kuvaava title-teksti sivuille

src/components/00-atoms/Input/index.js, src/components/02-organisms/CategorizedListRoot/CategorizedList/index.js, src/scenes/EsiJaPerusopetus/UusiAsiaDialog.js, src/scenes/EsiJaPerusopetus/lomake/6-Opiskelijamaarat.js, src/services/lomakkeet/esi-ja-perusopetus/6-opiskelijamaarat.js, src/services/lomakkeet/index.js
-Po 6. osio käyttämään uutta storea etc.
-Input komponentin valuen proptypeihin lisätty number
-isReadOnly true disabloi Dropdown -komponentin
=> CSCKUJA-498:

src/components/02-organisms/Asiakirjat/index.js, src/scenes/AmmatillinenKoulutus/AvoimetAsiat.js, src/scenes/EsiJaPerusopetus/AvoimetAsiat.js, src/scenes/Lukiokoulutus/AvoimetAsiat.js, src/scenes/VapaaSivistystyo/AvoimetAsiat.js, src/utils/asiatUtils.js, src/utils/constants.js
- Avoimet asiat taulukkorivin klikkaus ja asian esittelyyn vieminen ohjaa koulutustyypin mukaiseen osoitteeseen.
=> CSCKUJA-501 Avoimet asiat ja esittely navigoinnin korjaus.

src/scenes/Koulutusmuodot/EsiJaPerusopetus/Dialogit/Esittelijat/Lupanakyma/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/saving.js, src/services/lomakkeet/esi-ja-perusopetus/0-paatoksenTiedot.js
* Diaarinumerokenttä lisätty ja lomakkeen validointia päivitetty.
* Diaarinumero lähetetään tallennuksen yhteydessä. Backend vaatinee omat muutoksensa, jotta tallennus onnistuu ilman asianumeroa.
=> CSCOIVA-1659: Diaarinumero -kenttä syöttölomakkeelle

src/helpers/opetustehtavat/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuksenJarjestamismuoto.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetusJotaLupaKoskee.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuskielet.js
-Lisätty opetus, jota lupa koskee -osio PO-HTML lupaan.
-Korjattu osioiden tyylejä
=> CSCOIVA-1623: PO HTML Opetus jota lupa koskee ilman rajoituksia

src/components/03-templates/Jarjestaja/JulkisetTiedot.js, src/components/03-templates/Jarjestaja/Lupapaatokset.js, src/components/03-templates/Jarjestaja/LupapaatoksetTable/index.js, src/components/03-templates/Jarjestaja/index.js, src/components/03-templates/JarjestajaSwitch/index.js, src/i18n/definitions/common.js
- Kumottu ja päätöskirje sarake poistettu VST-lupien päätökset taulukosta.
- Otettu GetApp iconi käyttöön ja vaihdettu lupa ja päätöskirje linkkien nimiä.
=> CSCOIVA-1614 VST päätökset taulukosta poistettu sarakkeita.

src/i18n/definitions/education.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/Jarjestajaluettelo.js
-Esi- ja perusopetuksen kj listalta, maakuntasarake pois
-Koulutuksen järjestäjä -sarakkeen nimeksi Opetuksen järjestäjä
=> CSCOIVA-1662:

src/basedata.js, src/components/03-templates/Jarjestaja/Lupapaatokset.js, src/components/03-templates/Jarjestaja/LupapaatoksetTable/index.js, src/stores/lupahistoria.js
- Voimassaolevan VST-luvan asettaminen korjattu.
=> CSCOIVA-1673 VST-lupien historia haku korjattu.

src/components/03-templates/Jarjestaja/LupapaatoksetTable/index.js, src/components/03-templates/Jarjestaja/index.js
- VST-lupien järjestämislupa välilehden teksti muutettu ylläpitämisluvaksi.
=> CSCOIVA-1648 PO päätökset taulukon otsikko muutoksia.

src/index.js, src/scenes/Koulutusmuodot/AmmatillinenKoulutus/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardToimintaalue.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/lupanakymat/LupanakymaA.js, src/services/lomakkeet/esi-ja-perusopetus/2-opetustaAntavatKunnat.js
Oleellinen korjaus oli vaihtaa koodiArvo-sanasta A pienellä kirjoitetuksi.
=> CSCOIVA-1699: Toiminta-alueiden hakutoiminnossa pystytään hakemaan vaan maakunnilla ei kunnilla.

src/utils/asiatUtils.js
- Diaarinumero näytetään silloin jos ei ole annettu asianumeroa.
=> CSCOIVA-1685 Asiat taulukossa näytetään diaarinumero.

src/components/02-organisms/Lomake/index.js, src/components/03-templates/Asiat/index.js, src/components/03-templates/Jarjestaja/Jarjestamislupa-asiat.js, src/components/03-templates/Jarjestaja/JarjestamislupaAsiatList.js, src/components/03-templates/Jarjestaja/JulkisetTiedot.js, src/components/03-templates/Jarjestaja/OmatTiedot.js, src/components/03-templates/Jarjestaja/index.js, src/components/03-templates/KoulutusmuodonEtusivu/index.js, src/modules/styles.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/Dialogit/Esittelijat/Lupanakyma/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetustaAntavatKunnat.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/lupanakymat/LupanakymaA.js, src/stores/muutokset.js
=> CSCOIVA-1716: Sisältöelementtien yleiset tyylikorjaukset/-muutokset

src/components/03-templates/Jarjestaja/LupapaatoksetTable/index.js
- Päätöskirjettä ei näytetty jos luvalla oli diaarinumero eikä asianumero.
=> CSCOIVA-1708 Päätöskirje näkyy nyt myös PO luville.

src/services/lomakkeet/esi-ja-perusopetus/1-opetusJotaLupaKoskee.js, src/services/lomakkeet/esi-ja-perusopetus/4-opetuksenJarjestamismuoto.js, src/services/lomakkeet/esi-ja-perusopetus/5-erityisetKoulutustehtavat.js, src/services/lomakkeet/esi-ja-perusopetus/7-muutEhdot.js
- Lisätieto kentän koodiarvo 1 aiheutti jossain osioissa luvalt löytymättömän kohdan ilmestymisen html näkymään.
=> CSCOIVA-1723 PO html ylimääräisten määräysten korjaus.

src/scenes/Koulutusmuodot/AmmatillinenKoulutus/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuut.js
- Lomakkeen 5 kohdissa määräys uuid ei välittynyt oikein eri osioille.
=> CSCOIVA-1704 Ammatillisen lomakkeen kohdan 5 poistot korjattu.

src/helpers/poMuutEhdot/index.js
Toteutus ei vielä tässä vaiheessa huomioi määräyksiä.
=> CSCOIVA-1730: PO lomakkeella muokattu kuvaus muutos ei poistu jos valinta poistetaan

src/services/lomakkeet/esi-ja-perusopetus/esikatselu/3-opetuskielet.js
…antaa myös seuraavilla kielillä" otsikon "Opetuskieli" alaotsikoksi
=> CSCOIVA-1721: PO - Siirretään otsitkko "Opetusta voidaan..

src/services/lomakkeet/kielet/tutkintokielet/index.js
- Korjattu tyyli
- Korjattu kopioituminen
- Osaamisalat on laitettu piiloon tutkintokielet osiosta.
=> CSCOIVA-1764: Tutkintokielien bugit

src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js, src/utils/rajoitteetUtils.js
-Rajoitteen tallentuminen, kun opetuksen järjestämismuoto on kohteena
=> CSCOIVA-1765: Rajoituksen tallennus opetuksen järjestämismuoto kohteena

src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetustaAntavatKunnat.js, src/utils/rajoitteetUtils.js
-Täytesanat pois rajoitteilta
-PO-html lupaa ei saanut auki korjattu
-Rajoitteiden näyttämistä korjailtu
=> CSCOIVA-1769: Täytesanat pois rajoitteilta 

src/scenes/Koulutusmuodot/EsiJaPerusopetus/lomakeosiot/6-Opiskelijamaarat.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/lupanakymat/LupanakymaA.js, src/services/lomakkeet/esi-ja-perusopetus/esikatselu/6-opiskelijamaarat.js, src/utils/rajoitteetUtils.js
- Korjauksia listamuotoiseen esitykseen opiskelijamäärille.
=> CSCOIVA-1643 Opiskelijamäärä html ja esikatselu näkymään.

src/components/03-templates/Esittelijat/index.js, src/scenes/Koulutusmuodot/AmmatillinenKoulutus/UusiAsiaDialog.js
- Jos sivua ei ole määritelty käytetään sivun arvona 1:stä.
=> CSCOIVA-1779 Sivu parametri asetettu optionaaliseksi.

src/components/02-organisms/Asiakirjat/index.js, src/components/02-organisms/ConfirmDialog/index.js, src/components/03-templates/AvoimetAsiat/index.js, src/css/common.css
* `npm run tailwind:css` ennen testaamista.
=> CSCOIVA-1737: Dialogin padding & painiketyylin korjaus

src/components/02-organisms/Lomake/index.js, src/services/lomakkeet/opiskelijavuodet/index.js
-Vaativan tuen sekä sisäoppilaitosmuotoisen koulutuksen opiskelijavuosi - alert notifikaatio näkyviin oikein.
-Osiot topthree -ja opiskelijavuodet lomakedataan.
=> CSCOIVA-1666: Osion 5 vaativan erityisen tuen Alert-ilmoitus ei toimi oikein

src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoite.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/asetuksenKohdekomponentit.js
- Yksittäiselle opiskelijamäärä rajoitukselle voi nyt valita 2. kriteeristä eteenpäin kaikkia kohteita lomakkeelta.
=> CSCOIVA-1782 Yksittäisen opiskelijamäärän kriteerit.

src/helpers/rajoitteetHelper.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/kohteenTarkenninkomponentit.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoite.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/1-opetustehtavat.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/2-opetustaAntavatKunnat.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/3-opetuskielet.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/5-erityisetKoulutustehtavat.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/7-muutEhdot.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/asetuksenTarkenninkomponentit.js, src/utils/rajoitteetUtils.js
- Korjaus rajoitusten esitysmuotoon kun kyseessä on useampi kohdennus.
- Toiminta-alueen koodisto arvo korjattu opetustaAntavatKunnat -> kunnat.
=> CSCOIVA-1783 Monivalinta opiskelijamäärärajoituksissa.

src/components/03-templates/Jarjestaja/LupapaatoksetTable/index.js, src/utils/common.js
-Päivämääräsarakkeen mukaan sorttaaminen taulukoissa
=> CSCOIVA-1797: Pvm sarakkeen mukaan sorttaaminen

src/components/00-atoms/Datepicker/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/saving.js
Korjattu voimassaloppupvm tallentaminen
=> CSCOIVA-1801: Korjattu Datepicker

src/helpers/opetuskielet/index.js, src/helpers/opiskelijamaarat/index.js, src/helpers/rajoitteetHelper.js, src/i18n/definitions/opiskelijamaara.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetusJotaLupaKoskee.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuskielet.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opiskelijamaarat.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/lupanakymat/LupanakymaA.js, src/utils/rajoitteetUtils.js
-Opetus jota lupa koskee (CSCOIVA-1808)
-Opetuskielet (CSCOIVA-1803)
-Opiskelijamäärät (CSCOIVA-1806)
=> Cscoiva 1803, 1806, 1808

src/Oiva.js, src/components/02-organisms/Header/AuthenticationLink/index.js, src/components/02-organisms/Header/MobileMenu/index.js, src/components/02-organisms/Header/OrganisationLink/index.js, src/components/02-organisms/Header/index.js, src/components/02-organisms/SideNavigation/index.js, src/i18n/definitions/common.js, src/modules/i18n/components/LanguageSwitcher.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuksenJarjestamismuoto.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuskielet.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opiskelijamaarat.js, src/scenes/Saavutettavuusseloste/index.js, src/scenes/Tietosuojailmoitus/index.js, src/scenes/Yhteydenotto/index.js, src/static/images/close-icon.svg
-Mobiilivalikko
-Headerin muutokset < 768px
-Headerin muutokset < 1024px
=> CSCOIVA-1758: 1760: 1761: Headerin muutoksia

src/helpers/poErityisetKoulutustehtavat/index.js, src/helpers/poMuutEhdot/index.js
- 5. ja 7. osion muu erityinen koulutustehtävä / muu ehto valinnan poistaminen katoi lomakkeen.
=> CSCOIVA-1834 Muu erityinen koulutustehtävä valinnan korjaus.

src/components/00-atoms/TextBox/index.js
- 5. ja 7. osion muu erityinen koulutustehtävä / muu ehto kohdissa ensimmäisen kuvaus kentän arvo ei rederöitynyt aina käyttöliittymään.
=> CSCOIVA-1833 PO-lomake kuvaus teksti korjaus.

src/Oiva.js, src/components/02-organisms/Asiakirjat/index.js, src/components/03-templates/Asianhallinta/index.js, src/components/03-templates/KoulutusmuodonEtusivu/index.js
=> CSCOIVA-1835: Kirjautumaton käyttäjä päääsee asianhallintaan

src/scenes/Koulutusmuodot/EsiJaPerusopetus/kaikkiPOosiotTaytetty-muutokset.js, src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/asetuksenKohdekomponentit.js
Päivitetty samalla testidataa kattavammaksi.
=> CSCOIVA-1843: PO-lomake Erityisen koulutustehtävän rajoitteissa ei pysty valitsemaan kriteereitä

src/helpers/lukioErityisetKoulutustehtavat/index.js, src/scenes/Koulutusmuodot/Lukiokoulutus/saving.js, src/services/lomakkeet/esi-ja-perusopetus/5-erityisetKoulutustehtavat.js, src/services/lomakkeet/index.js, src/services/lomakkeet/lukiokoulutus/4-erityisetKoulutustehtavat.js
HUOM! Tämä PR sisältää myös bugikorjauksen esi- ja perusopetuksen 5. Erityinen koulutustehtävä -osioon. Piste puuttui.
=> CSCOIVA-1795: 4. LUKIO - Erityinen koulutustehtävä osio - Tallennus

src/helpers/opetuksenJarjestamismuodot/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuksenJarjestamismuoto.js
- Kuvaus tallentuu tietokantaan oikein.
- Kuvaus näytetään html lupa näkymässä.
=> CSCOIVA-1859 PO opetuksen järjestämismuodon kuvaus korjaus.

package-lock.json, package.json, src/components/00-atoms/Input/input.module.css, src/components/00-atoms/TextBox/textbox.module.css, src/components/01-molecules/RadioButtonWithLabel/radio-button.module.css
Downgradettu tailwindcss paketti takaisin ^1.95 (>=2.0.0 ei toimi node 8:lla)
Downgradettu poscss-cli paketti takaisin ^6.1.3 (>=7.0.0 ei toimi node 8:lla)
=> CSCOIVA-1863: Frontend buildin korjaus

src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/muutEhdot.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuksenJarjestamismuoto.js, src/services/lomakkeet/utils.js
- Korjattu myös muutehdot kohdan kuvaus.
=> CSCOIVA-1866 Opetuksen järjestamismuodon kuvaus näkyviin html:ään.

src/i18n/definitions/common.js, src/i18n/definitions/esiJaPerusopetus.js, src/i18n/definitions/lukiokoulutus.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/index.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/erityisetKoulutustehtavat.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/index.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/muutEhdot.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/opetuskielet.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/opetustaAntavatKunnat.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/opiskelijamaarat.js, src/services/lomakkeet/esi-ja-perusopetus/esikatselu/0-paatoksenTiedot.js, src/utils/rajoitteetUtils.js
* PR sisältää myös issueiden CSCOIVA-1832, CSCOIVA-1825, CSCOIVA-1829 ja CSCOIVA-1831 koodit.
=> CSCOIVA-1821: 2. LUKIO - Opetuskieli osio HTML - lupanäkymä

src/helpers/opiskelijamaarat/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/saving.js, src/scenes/Koulutusmuodot/Lukiokoulutus/saving.js
-Haetaan kohde oikealla tunnisteella
=> CSCOIVA-1889: Opiskelijamäärät osion tallennus toimimaan lukiopuolella

src/modules/navigation/components/Navigation.js
CSOIVA-1904: Päänavigaation näppäimistönavigointi
=> CSCOIVA-1903: Navigaation 2.tason hover

src/modules/navigation/components/Navigation.js
CSCOIVA-1903 automerge oli ajanut tämän korjauksen yli.
=> CSCOIVA-1903 Mergessä hävinnyt korjaus

src/helpers/ammatillinenKoulutus/tallentaminen/esittelijat.js, src/helpers/muut/index.js, src/scenes/Koulutusmuodot/AmmatillinenKoulutus/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuut.js, src/services/lomakkeet/ammatillinenKoulutus/5-muut/muuMaarays.js, src/services/lomakkeet/ammatillinenKoulutus/5-muut/yhteistyosopimus.js, src/utils/lupaParser.js
Sisältää myös CSCOIVA-1298 (Muun määräyksen näkyminen ja tallentaminen lomakkeella)
=> CSCOIVA-1540: Yhteistyösopimuksen muokkaaminen / näkyminen html-luvalla

src/helpers/opetustaAntavatKunnat/index.js, src/helpers/rajoitteetHelper.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/saving.js
* HUOM! PR ei sisällä tallennustoimintoja. Niille on luotu omat issuet CSCOIVA-1885:n alle.
=> CSCOIVA-1893: PO: Mahdollistetaan lupaan jo kuuluvien valintojen käyttäminen rajoitteissa

src/helpers/lukioErityisetKoulutustehtavat/index.js, src/helpers/opetuksenJarjestamismuodot/index.js, src/helpers/opetuskielet/index.js, src/helpers/rajoitteetHelper.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/saving.js, src/scenes/Koulutusmuodot/Lukiokoulutus/saving.js, src/services/lomakkeet/rajoitteet/rajoitedialogi/tarkenninkomponentit/esi-ja-perusopetus/4-opetuksenjarjestamismuoto.js, src/services/lomakkeet/rajoitteet/rajoitedialogi/tarkenninkomponentit/yhteiset/kunnat.js, src/utils/rajoitteetUtils.js
* PR sisältää myös issueiden CSCOIVA-1922 ja CSCOIVA-1927 koodit.
=> CSCOIVA-1926: LUKIO: Rajoitteita määräyksiin - 1. Kunnat, joissa opetusta järjestetään

src/scenes/Koulutusmuodot/EsiJaPerusopetus/lomakeosiot/5-ErityisetKoulutustehtavat.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/lomakeosiot/7-MuutEhdot.js, src/services/lomakkeet/esi-ja-perusopetus/5-erityisetKoulutustehtavat.js, src/services/lomakkeet/esi-ja-perusopetus/7-muutEhdot.js, src/stores/muutokset.js
Sisältää myös CSCOIVA-1912 korjaukset.
=> CSCOIVA-1911: PO-lomake 5. Osio lisättävät tekstikentät bugi

src/basedata.js, src/stores/utils/backendRoutes.js
-luvat/organisaatiot minimumTimeBetweenFetchingInMinutes 0
=> CSCOIVA-1887: KJ näkyville Luo uusi asia dialogin dropdowniin heti kun lupa luotu

src/services/lomakkeet/lukiokoulutus/0-paatoksenTiedot.js
* Vastaava toteutus, kuin PO-puolella.
=> CSCOIVA-1958: Lukiolomake: Kenttä diaarinumerolle puuttuu

src/helpers/lukioMuutEhdot/index.js, src/scenes/Koulutusmuodot/Lukiokoulutus/saving.js
- 7. Muut koulutuksen järjestämiseen liittyvät ehdot
=> CSCOIVA-1932: LUKIO: Rajoitteita määräyksiin

src/components/00-atoms/SimpleButton/index.js, src/components/02-organisms/CategorizedListRoot/CategorizedList/index.js, src/components/02-organisms/RajoitteetList/index.js, src/i18n/definitions/rajoitteet.js, src/services/lomakkeet/rajoitteet/index.js
-Lisää rajoite -nappi käyttämään secondary tyylejä
-Poista rajoite -nappi tekstimuotoiseksi ja delete-ikoni eteen
-Muokkaa nappi poistettu rajoiteboksista
=> CSCOIVA-1989: Lomakkeen rajotetoiminnon painikkeet

src/scenes/Koulutusmuodot/VapaaSivistystyo/Jarjestajaluettelo.js
- Lupia voidaan nyt filteröidä oppilaitostyypillä myös ruotsiksi.
=> CSCOIVA-2008 VST oppilaitostyyppi filteröinti korjaus.

src/helpers/opetustehtavat/index.js
-Lisätty määräysUuid muutos-objektille, jos kyseessä poisto
=> CSCOIVA-1908: Opetustehtävämääräyksien poistaminen bugfix

src/helpers/lukioErityisetKoulutustehtavat/index.js
- Korjattu mergestä johtuneet ongelmat.
=> CSCOIVA-1930: LUKIO: Rajoitteita määräyksiin - 5. Valtakunnallinen kehittämistehtävä

src/services/lomakkeet/rajoitteet/rajoitedialogi/tarkenninkomponentit/lukiokoulutus/3-oikeusSisaoppilaitosmuotoiseenKoulutukseen.js, src/services/lomakkeet/rajoitteet/rajoitedialogi/tarkenninkomponentit/yhteiset/erityisetKoulutustehtavat.js, src/services/lomakkeet/rajoitteet/rajoitedialogi/tarkenninkomponentit/yhteiset/muutEhdot.js, src/utils/rajoitteetUtils.js
- Dynaamisten tekstikenttien kuvaus tekstiä näytetään oikein lupa html:ssä ja lomake esikatselu.
=> CSCOIVA-2019 Tekstikenttien kuvauksen näyttäminen.

src/components/02-organisms/RajoitteetList/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetustaAntavatKunnat.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/opetustaAntavatKunnat.js, src/utils/rajoitteetUtils.js
-Korjattu kuntien näyttäminen PO ja lukiopuolen html-luvilla.
-Luotu funktio getValueFromAlimaarays, joka hakee alimääräyksen näytettävän arvon alimääräyksen ominaisuuksien perusteella.
-Käytetään tätä funktiota käsiteltäessä alimääräyksiä.
=> CSCOIVA-2033: -Korjattu ulkomaiden näyttäminen rajoitelaatikossa lomakkeella.
