CSCfi/oiva-frontend

src/routes/Jarjestajat/Jarjestaja/components/Jarjestamislupa.js, src/routes/Jarjestajat/Jarjestaja/components/LupaSection.js
Kirjautuneena koulutuksen järjestäjänä järjestämislupa-välilehdellä ei enää näytetä hae muutosta/katso muutosta -linkkiä.
=> CSCOIVA-548: Poista linkki järjestäjän näkymästä

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuutokset.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardTutkinnot.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardTutkintokielet.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/TutkintoKieliList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/MuutospyyntoWizardTutkintokieletContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js
Hakemuksen kohta 2 näytti aiemmin kaikki luvasta löytyvät tutkinnot ja koulutukset. Kohtaa muutettiin niin, että kohdassa näytetään
- luvasta löytyvät sekä 
- kohdassa yksi lupaan lisätyt tutkinnot ja koulutukset,
mutta ei kuitenkaan
- kohdassa yksi luvasta poistettuja tutkintoja ja koulutuksia eikä
- käytöstä jo poistuneita tutkintoja ja koulutuksia. (Jos sitä ei ole mahdollista hakea lupaan lisättäväksi, sille ei pitäisi pystyä valitsemaan myöskään tutkintokieltä.)
Mahdollisten koulutusten ja tutkintojen lista haetaan nyt kohdissa yksi ja kaksi yhteisellä koodilla, joka siirtyi MuutospyyntoWizardTutkinnot-komponentista askeleen ylemmäs MuutospyyntoWizardMuutokset-komponenttiin.
=> CSCOIVA-570: Tutkintokielilistan korjauksia

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardOpiskelijavuodet.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/constants.js
Opiskelijavuosikenttiä renderöidessä tarkastetaan
- onko käyttäjä lisännyt lupaan muun vaatimuksen sisäoppilaitosmuotoisesta tai vaativan tuen koulutuksesta,
- onko edelliseen vaatimukseen liittyvä opiskelijavuosimääräkenttä tyhjä ja 
- eikö kyseinen kenttä ole tällä hetkellä näkyvissä selaimessa.
Jos kaikki ehdot täyttyvät, sivu skrollataan kentän luokse.
Lisäksi aina kun yo. kentät ovat mukana lomakkeella, niiden otsikot esitetään keltaisen taustavärin kanssa.
=> Ilmoita käyttäjälle pakollisista opiskelijavuosikentistä

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutosYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelu.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluOppisopimus.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluOppisopimusYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluTyovoima.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVaativa.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVankila.js
Näytä oppisopimuskoulutuksen hakemiseen liittyvät perustelut muutospyynnön yhteenvedossa.
Perustelulomakkeista löytyi pieni bugi, joka tallensi kaikki kohdan "Arvio koulutukseen suunnattavista opiskelijavuosista seuraavana kolmena vuotena" vastaukset samalle vuosinumerolle. Korjattu muiden muutosten yhteydessä.
=> CSCOIVA-583: Oppisopimuskoulutuksen perustelut yhteenvetoon

src/modules/reducers/vankilat.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutosYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoEditWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelu.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluOppisopimusYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVankila.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVankilaYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/MuutospyyntoEditWizardContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/MuutospyyntoWizardContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/PerusteluContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/vankilaUtil.js, src/store/reducers.js
Näyttää yhteenvedossa vankilakoulutuksen perustelut.
Ei näytä vielä suunnitelma-kentän (dropdown vankiloista) arvoa, koska sitä ei ole toteutettu Reduxiin. Näyttää vankilan nimen paikalla placeholder-tekstin.
=> CSCOIVA-587: Näytä vankilakoulutuksen perustelut yhteenvedossa

src/modules/reducers/elykeskukset.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutosYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoEditWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Perustelu.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluTyovoima.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluTyovoimaYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVaativaYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVankilaYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/MuutospyyntoEditWizardContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/MuutospyyntoWizardContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/PerusteluContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/ELYkeskusUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/vankilaUtil.js, src/store/reducers.js
Työvoimakoulutuksen perusteluissa näytettävä lista ELY-keskuksista haetaan koodistosta. Valittu ELY-keskus tallennetaan formin stateen. Annetut perustelut näytetään yhteenvedossa.
Korjaa myös bugin, jossa yhteenveto heitti errorin, jos vankilakoulutuksen perusteluissa oli jätetty vankila valitsematta.
=> CSCOIVA-595: Työvoimakoulutuksen perustelut loppuun

src/routes/Login/containers/CasAuthenticated.js
Kun käyttäjä kirjautuu sisään, ohjaa hänet oman organisaation sivulle heti kun tieto tulee komponentin saataville. Jos käyttäjällä ei ole organisaatiota, näkyviin jää teksti "Tervetuloa Oiva-palveluun [käyttäjän nimi]".
=> CSCOIVA-494: Edelleenohjaa kirjautunut käyttäjä organisaation sivulle

src/modules/Header/components/Header.js
Hakee käyttäjän roolit ja organisaatiot jo navigaatiopalkkia luodessa ja näyttää tarvittaessa linkin "Oma organisaatio".
=> CSCOIVA-600: Lisää 'Oma organisaatio' päänavigaatioon

src/modules/reducers/koulutustyypit.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Muutos.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutosListTutkinnot.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoEditWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizard.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardComponents.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardMuutokset.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPerustelut.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardTutkinnot.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/TutkintoKieliList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/TutkintoList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/MuutospyyntoEditWizardContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/containers/MuutospyyntoWizardContainer.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusParser.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js, src/routes/Jarjestajat/Jarjestaja/modules/constants.js, src/store/reducers.js
Muutoshakemuksen muutos-, perustelu- ja yhteenvetovälilehtien tutkinto- ja tutkintokielilistauksissa tutkinnot järjestetään koulutusaloittain, koulutustyypeittäin ja aakkosittain. Koulutusalat ja -tyypit näytetään väliotsikkoina.
Osaamisalat näytetään tutkintolistoilla niihin liittyvien tutkintojen alapuolella. Jos tutkinto ei ole mukana muutospyynnössä, osaamisala näytetään siinä kohtaa, johon tutkinto kuuluisi.
Myös koulutuksille ja opetuskielille lisättiin väliotsikot selkeyden takia.
=> CSCOIVA-512 Tutkintojen uudelleenjärjestys ja väliotsikointi

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardComponents.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluKuljettajaJatko.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluKuljettajaPerus.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluOppisopimus.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluOppisopimusYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluSimple.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluTyovoima.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluTyovoimaYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVaativa.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVaativaYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVankila.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluVankilaYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/TaloudellisetYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/constants.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/koulutusUtil.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/lisaperusteluUtil.js
Muutokset molempiin kuljettajakoulutusten perustelulomakkeisiin:
- Ammattipätevyys:
-- Checkbox muutettu kahdeksi radiovalinnaksi
-- Päivämääräkentän komponentti vaihdettu tekstikentästä react-datepickeriin
- Opettajien pätevyys:
-- Mahdollisuus lisätä useita opettajia
-- Tehdyt valinnat tallennetaan muutospyyntöön
- Ajoneuvokanta:
-- Kenttien tyyppi muutettu tekstistä numeroksi
-- Muut, mitä -kenttä poistettu
=> CSCOIVA-646: Kuljettajakoulutusten perustelulomakkeiden muutoksia

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/KoulutusList.js
Muutospyynnössä ammatilliseen tehtävään valmistavien koulutusten kohdalla näytetään kuvaus, ei nimi.
=> CSCOIVA-659 Vaihda ammatilliseen tehtävään valmistavan koulutuksen nimikkeet

src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Liite.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Liitteet.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutosList.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutosListTutkinnot.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardPerustelut.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardYhteenveto.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluKuljettajaJatko.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/PerusteluKuljettajaPerus.js, src/routes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/modules/uusiHakemusFormConstants.js
Tehty:
Liitteiden sijanteihin muutoksia yhteenvedossa
Korjattu liitteiden nimeämistä
Tuki enter-näppäimen painamiselle nimeämisen dialogille
Sisennykset
Korjattu nimeäminen
EI TEHTY:
Yhteenvedossa eivät vielä tehty kuljettakoulusten liitteet (yhteenveto tekemättä)
Taloudelliset edellytykset odottaa liitteiden metatieto-tukea backendiltä
=> Cscoiva 713: Yhteenvedon liitteet

src/services/muutoshakemus/utils/tutkinnotUtils.js
Tutkinto title was wrongly being set to a bold font weight. This fix removes the custom style and affects Perustelut and Yhteenveto views in MuutospyyntoWizard.
=> CSCKIJA-163 fix

src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardOpiskelijavuodet.js
Fixes the react-hooks/exhaustive-deps linter warning for MuutospyyntoWizardOpiskelijavuodet. No longer having the unhygienic use of spread operator for useState variable.
* Making sure that we set full constraintFlags on first render's useEffect.
* Properly using previous state for constraintFlags in useEffect based on section 5 changes.
=> Cscoiva 507 2

src/components/02-organisms/Difference/index.js, src/scenes/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/MuutospyyntoWizardOpiskelijavuodet.js
* Now using the same mechanism to set initial component properties (initialValue, applyForValue) for sisaoppilaitos and vaativatuki as with opiskelijavuodet with Difference component. Setting initialValue was missing.
* Removed the unworking changesOfSection5 based useEffect which had been used to set values previously.
* Simplified the exclusion of sisaoppilaitos and vaativatuki changes when no longer needed.
=> Cscoiva 988

src/scenes/Jarjestajat/components/Jarjestajaluettelo.js
WWW-sarake poistettu taulukosta.
=> CSCOIVA-1494: Koulutuksenjärjestäjien uuden hakutaulukon "www" - sivujen poisto

src/scenes/Home/index.js
Only h2 in typography is changed to h1 for accessibility reasons
=> CSCOIVA-1460 changed h2 to h1 in frontpage

src/scenes/Esittelijat/UusiAsiaEsidialog.js
Jätetään tyhje y-tunnuksen edessä ja takana huomioimatta.
=> CSCOIVA-1501: Välilyönti y-tunnushaun edessä aiheuttaa haun epäonnistumisen

src/basedata.js, src/helpers/kielet/index.js, src/helpers/opetuskielet/index.js, src/scenes/EsiJaPerusopetus/AsiaDialogContainer.js, src/scenes/EsiJaPerusopetus/UusiAsiaDialog.js, src/scenes/EsiJaPerusopetus/UusiAsiaDialogContainer.js, src/scenes/EsiJaPerusopetus/lomake/3-Opetuskieli.js, src/services/lomakkeet/esi-ja-perusopetus/3-opetuskielet.js, src/services/lomakkeet/index.js
* kieletOPH:n jakaminen kahteen eri muuttujaan: ensisijaisetOpetuskieletOPH ja toissijaisetOpetuskieletOPH
* Pudotusvalikoissa ei näytetä niitä kieliä, jotka ovat jo valittuina.
* Komponenttipuolelle kohdistui myös muutoksia.
=> CSCKUJA-483: Opetuskielivalikkoon kaikki kielet

src/components/00-atoms/SimpleButton/index.js, src/components/00-atoms/TextBox/index.js, src/components/01-molecules/CheckboxWithLabel/index.js, src/components/01-molecules/RadioButtonWithLabel/index.js, src/components/02-organisms/CategorizedListRoot/CategorizedList/index.js, src/components/02-organisms/CategorizedListRoot/index.js, src/components/02-organisms/ExpandableRowRoot/index.js, src/components/02-organisms/Lomake/index.js, src/i18n/definitions/common.js, src/index.js, src/scenes/AmmatillinenKoulutus/Esittelijat/Lupanakyma/Osiot/Muut/08-Yhteistyosopimus/index.js, src/scenes/AmmatillinenKoulutus/store.js, src/scenes/EsiJaPerusopetus/UusiAsiaEsidialog.js, src/scenes/EsiJaPerusopetus/lomake/5-ErityisetKoulutustehtavat.js, src/services/lomakkeet/esi-ja-perusopetus/5-erityisetKoulutustehtavat.js, src/utils/common.js
* Suunniteltu ja toteutettu mekanismi fokuksen asettamiseksi. Fokuksen siirtymistä voi hallita lomakepalvelun puolella lomakemerkkauksesta käsin asettamalla komponentille forChangeObject-objektiin ominaisuuden `focusWhenDeleted` ja arvoksi jonkin lomakkeen ankkurin. Tilanhallintaa on laajennettu `focusOn`-ominaisuudella, joka välitetään komponenteille Lomake-komponenttia hyödyntäen.
* Otettu ratkaisu käyttöön PO-puolen osiossa 5. Mikäli ratkaisu todetaan toimivaksi katselmoinnin myötä, voidaan kirjoittaa Jiraan uudet issuet sen mukaan, mihin muihin osioihin ratkaisu on otettava käyttöön.
=> CSCOIVA-1594: Fokus kun tekstikenttien lisäys- ja poistotoiminnallisuutta käytetään näppäimistöllä

src/components/02-organisms/Asiakirjat/index.js, src/components/03-templates/Section/index.js, src/index.js, src/modules/Loading.js, src/scenes/Koulutusmuodot/AmmatillinenKoulutus/JarjestamislupaHTML/LupaSection.js, src/scenes/Koulutusmuodot/AmmatillinenKoulutus/JarjestamislupaHTML/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/erityisetKoulutustehtavat.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/muutEhdot.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuksenJarjestamismuoto.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetusJotaLupaKoskee.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuskielet.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetustaAntavatKunnat.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opiskelijamaarat.js
Toteutettu tässä sekä CSCOIVA-1664, että CSCOIVA-1676 
- Lisätiedot näkyviin PO html-luvan osioille
- Korjattu PO html-lupa käyttämään Typography-elementtiä h-elementtien sijaan
- Myös Ammatillisen puolen luvalla käytetään nyt Typography-elementtiä.
- Vaihdettu myös muutamaan muuhun paikkaan h-elementti Typography-elementtiin...
=> Cscoiva 1664 ja CSCOIVA-1676

src/scenes/Koulutusmuodot/VapaaSivistystyo/JarjestamislupaHTML/LupaSection.js, src/scenes/Koulutusmuodot/VapaaSivistystyo/JarjestamislupaHTML/index.js
-Korjattu VST puolen html-lupien otsikoiden tyylejä
=> CSCOIVA-1676: Html lupien otsikoiden fonttityylit

src/components/03-templates/Asiat/index.js, src/components/03-templates/Esittelijat/index.js, src/components/03-templates/KoulutusmuodonEtusivu/index.js, src/index.js, src/scenes/Koulutusmuodot/AmmatillinenKoulutus/EsittelijatMuutospyynto.js, src/scenes/Koulutusmuodot/AmmatillinenKoulutus/Jarjestajat/Jarjestaja/Hakemukset/Muutospyynto/components/Kielet/Tutkintokielet.js
-Asetettu typography h-elementeille paddingTop ja paddingBottom 1rem
-Käytetään ammatillisen puolen muutospyyntölomakkeella Typography-elementtejä
=> CSCOIVA-1679: Asiat -sivun tyylit

tailwind.js
* Aja `npm run tailwind:css`, jotta tailwind.css päivittyy ja virheelliset CSS-määritykset poistuvat.
=> CSCOIVA-1798: Frontendin npm build rikki

src/components/02-organisms/Header/MobileMenu/index.js, src/components/02-organisms/Header/index.js
Päädyin ratkaisuun, jossa mobiilivalikon kohta "Järjestämis- ja ylläpitämisluvat" on koko ajan avattuna. Itse pääsivulle "Järjestämis- ja ylläpitämisluvat" ei mobiilivalikosta käsin pääse, mutta se lienee ok viitaten issueen CSCOIVA-1846, jonka kuvauksessa on teksti "erillistä Järjestämis- ja ylläpitämisluvat -päätason sivua näin ollen tarvita".
=> CSCOIVA-1847: Mobiilinavigaation navigointi näppäimistöllä

src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/erityisetKoulutustehtavat.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/muutEhdot.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuksenJarjestamismuoto.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetusJotaLupaKoskee.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuskielet.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetustaAntavatKunnat.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opiskelijamaarat.js, src/utils/rajoitteetUtils.js
- Alimääräyksiä käsitellessä i18n-for-browser ei ole käytettävissä silloin kun sitä tarvitaan.
=> CSCOIVA-1948 Korjattu PO html luvan alimääräys bugi.

src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetuskielet.js
- Ensisijaiset- ja toissijaisetopetuskielet erotellaan määräyksen meta kentän 'valikko' avulla.
=> CSCOIVA-1950 PO-opetuskielet HTML korjaus.

src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/opetusJotaLupaKoskee.js
- Jenkins käyttää automaatisesti process.env.CI = true parametria, jolloin compile varoitukset käsitellään virheinä ja buildi ei mene läpi.
=> CSCOIVA-1990 CI buildi varoituksien korjaus.

src/helpers/ammatillinenKoulutus/tallentaminen/esittelijat.js, src/helpers/lukioErityisetKoulutustehtavat/index.js, src/helpers/lukioMuutEhdot/index.js, src/helpers/poErityisetKoulutustehtavat/index.js, src/helpers/poMuutEhdot/index.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/erityisetKoulutustehtavat.js, src/scenes/Koulutusmuodot/EsiJaPerusopetus/JarjestamislupaHTML/muutEhdot.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/erityisetKoulutustehtavat.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/muutEhdot.js, src/scenes/Koulutusmuodot/Lukiokoulutus/JarjestamislupaHTML/valtakunnallisetKehittamistehtavat.js, src/scenes/Koulutusmuodot/Lukiokoulutus/lomakeosiot/5-ValtakunnallisetKehittamistehtavat.js, src/scenes/Koulutusmuodot/Lukiokoulutus/lupanakymat/LupanakymaA.js, src/services/lomakkeet/dynamic.js, src/services/lomakkeet/esi-ja-perusopetus/5-erityisetKoulutustehtavat.js, src/services/lomakkeet/esi-ja-perusopetus/7-muutEhdot.js, src/services/lomakkeet/lukiokoulutus/4-erityisetKoulutustehtavat.js, src/services/lomakkeet/lukiokoulutus/5-valtakunnallinenKehittamistehtava.js, src/services/lomakkeet/lukiokoulutus/7-muutEhdot.js
- Sisältää sekä CSCOIVA-1994 että CSCOIVA-1905 koodit (määräysten huomioon ottaminen osiossa 5)
- Luodaan tarvittavat muutos-objektit, kun määräyksiä lisätään/poistetaan/muokataan
- Ei tallenneta kuvausta lainkaan, jos tekstikentän sisältö sama kuin koodistosta saatu arvo.
- Lukion osio 4 ei käytä samoja funktioita kuin muut kolme dynaamisia tekstikenttiä sisältävää osiota, koska siihen liittyy valtakunnalliset kehittämistehtävät
=> CSCOIVA-1994: -Dynaamisten tekstikenttien tallennus toimimaan oikein

public/index.html, src/components/02-organisms/ConfirmDialog/index.js, src/components/02-organisms/DialogTitle/index.js, src/components/03-templates/AvoimetAsiat/index.js, src/index.js, src/modules/constants.js, src/utils/asiatUtils.js
* ConfirmDialog-komponentin tyylit muokattu toivotunlaisiksi (esim. Merkitse päätetyksi -dialogi).
* Material-UI:n breakpointit asetettu arvoiltaan samoiksi, kuin TailwindCSS:n breakpointit.
* Huom! Muut kuin ConfirmDialog:ia pohjanaan käyttävät dialogit eivät korjaannu tämän PR:n koodeilla.
=> CSCOIVA-2002: Dialogin korjaukset
